queue_rules:
- name: fido-device-onboard-rs
  conditions:
    - base=main
    - "#approved-reviews-by>=1"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - base=main
    - "#approved-reviews-by>=1"
    - "label!=possible stability impact"
    actions:
      queue:
        name: fido-device-onboard-rs
        method: merge

  - name: Automatic merge on approval (stability impact no impact)
    conditions:
    - base=main
    - "#approved-reviews-by>=1"
    - "label=possible stability impact"
    - "label=stability impact assessed: no impact"
    actions:
      queue:
        name: fido-device-onboard-rs
        method: merge


  - name: Automatic merge on approval (stability impact)
    conditions:
    - base=main
    - "#approved-reviews-by>=2"
    - "label=possible stability impact"
    actions:
      queue:
        name: fido-device-onboard-rs
        method: merge
