queue_rules:
- name: fido-device-onboard-rs
  conditions:
    - base=main
    - "#approved-reviews-by>=1"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - base=main
    - "#approved-reviews-by>=1"
    actions:
      queue:
        name: fido-device-onboard-rs
        method: rebase
        rebase_fallback: none
