queue_rules:
  - name: duplicated fido-device-onboard-rs from Automatic merge on approval
    queue_conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "label!=possible stability impact"
    merge_conditions:
      - base=main
      - "#approved-reviews-by>=1"
    merge_method: merge
  - name: duplicated fido-device-onboard-rs from Automatic merge on approval (stability impact
      no impact)
    queue_conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "label=possible stability impact"
      - "label=stability impact assessed: no impact"
    merge_conditions:
      - base=main
      - "#approved-reviews-by>=1"
    merge_method: merge
  - name: duplicated fido-device-onboard-rs from Automatic merge on approval (stability impact)
    queue_conditions:
      - base=main
      - "#approved-reviews-by>=2"
      - "label=possible stability impact"
    merge_conditions:
      - base=main
      - "#approved-reviews-by>=1"
    merge_method: merge

pull_request_rules:
  - name: Automatic merge on approval + Automatic merge on approval (stability impact no
      impact) + Automatic merge on approval (stability impact)
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `duplicated fido-device-onboard-rs from Automatic merge on approval`
    conditions:
      - "label!=possible stability impact"
    priority: 2500
  - name: priority for queue `duplicated fido-device-onboard-rs from Automatic merge on approval
      (stability impact no impact)`
    conditions:
      - "#approved-reviews-by>=1"
      - "label=stability impact assessed: no impact"
    priority: 2250
