---
# https://packit.dev/docs/configuration/

specfile_path: fido-device-onboard.spec

files_to_sync:
    - fido-device-onboard.spec
    - .packit.yaml

upstream_package_name: fido-device-onboard
downstream_package_name: fido-device-onboard

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
    - cargo
    - openssl-devel

jobs:
    - &fdo_copr_build
      job: copr_build
      trigger: pull_request
      targets:
          epel-9: {}
          fedora-latest-stable: {}
          fedora-latest: {}
          fedora-rawhide: {}
          fedora-eln:
              additional_repos:
                  - https://kojipkgs.fedoraproject.org/repos/eln-build/latest/$basearch/

    - job: tests
      trigger: pull_request
      identifier: onboarding
      fmf_path: test/fmf
      tmt_plan: plans/onboarding
      targets:
          epel-9: {}
          fedora-latest-stable: {}
          fedora-latest: {}
          fedora-rawhide: {}

    - <<: *fdo_copr_build
      trigger: commit
      branch: main
      owner: "@fedora-iot"  # copr repo namespace
      project: fedora-iot   # copr repo name so you can consume the builds
...
