#!/bin/bash

set -e

# these will come from https://github.com/osbuild/osbuild-composer/pull/1884, along with rootcert config and other things
MANUFACTURING_SERVICE_URL="http://fdo-test.puiterwijk.org:8080" DIUN_PUB_KEY_INSECURE="true" \
/usr/bin/fdo-manufacturing-client

mkdir -p /bootmount
TYPE=$(lsblk --output FSTYPE /dev/disk/by-label/boot | tail -n1)
mount -t ${TYPE} /dev/disk/by-label/boot /bootmount
cp -a /etc/fdo/device-credentials /bootmount/device-credentials